### ISSUE TITLE
Todo: Everything

### ISSUE THREAD

**Issue by elisaado** [elisaado/steps-to#2]
- [x] Make the landing page nice
- [x] Replace the guide list with a search bar on the landing page
- [x] Make everything look good
- [x] Implement API
